pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-course')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login'){
            steps{
                bat encoding: 'UTF-8', script: 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Pull image'){
            steps{
                bat encoding: 'UTF-8', script:'''
                        docker pull asoldatenkov/mle-course:latest
                '''
            }
        }

        stage('Run container'){
            steps{
                bat '''
                        docker run --name mle-course -p 80:5556 -d asoldatenkov/mle-course:latest
                '''
            }
        }
		stage ('Invoke CD pipeline') {
            steps {
                build job: 'mle-course-CD'
            }
        }
	}

    post {
        always {
            bat 'docker stop mle-course && docker logout'
        }
    }
}
